drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title text NOT NULL,
    url text NOT NULL,
    rating INTEGER DEFAULT 1,
    description text,
)

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, rating, description)
values
    ('Google', 'http://www.google.com', '3', 'Internet-related services and products.'),
    ('Thinkful', 'http://www.thinkful.com', '5', '1-on-1 learning to accelerate your way to a new high-growth tech career!'),
    ('Github', 'http://www.github.com', '4', "brings together the world's largest community of developers."),
    ('React', 'https://reactjs.org/', '5', 'A JavaScript library for building user interfaces'),
    ('Nodejs', 'https://nodejs.org/en/', '3', 'As an asynchronous event-driven JavaScript runtime, Node.js is designed to build scalable network applications.'),
    ('Stack overflow', 'https://stackoverflow.com/', '5', 'We build products that empower developers and connect them to solutions that enable productivity, growth, and discovery.'),
    ('Jquery', 'https://developer.mozilla.org/en-US/', '3', 'jQuery is a fast, small, and feature-rich JavaScript library'),
    ('MDN', 'https://nodejs.org/en/', '3', 'Resources for developers, by developers.'),
    ('WWW3', 'https://www.w3schools.com/', '5', 'The language for building web pages'),
    ('PostgreSQL', 'https://www.postgresql.org/', '4', "The World's Most Advanced Open Source Relational Database.");
